### ISSUE TITLE
[FINAL TOUCHES] repharse comparison

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#106]
> "Your team has 2.4% better Work Experience than the rest."

^ users found it vague

Can you change for example to:

> "You hired people with 2.4% more Work Experience than the average applicant."

(Up for discussion)

**Comment by AliaElKattan** [comment]
@jihjihk  are we keeping this stat in manual hiring?

**Comment by jihjihk** [comment]
Yep
