### ISSUE TITLE
[FINAL TOUCHES] browser compatibility

### ISSUE THREAD

**Issue by AliaElKattan** [AliaElKattan/survivalofthebestfit#119]
check sizes & responsiveness on diff browsers (esp. chrome)

**Comment by gaborcsapo** [comment]
Linux, chrome, 1080p full screen --- People float
![Screenshot from 2019-05-30 21-44-56](https://user-images.githubusercontent.com/13856404/58664358-65b70580-8326-11e9-933c-3704959f68d3.png)

**Comment by AliaElKattan** [comment]
![image](https://user-images.githubusercontent.com/7271371/59153781-e8486f00-8a62-11e9-8e92-f2014e277bc3.png)

windows, chrome
