### ISSUE TITLE
Clear office container when the stage restarts after time out

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#12]
Right now office, person and desk containers are global so when a stage has to be repeated due to time out, the desks/floor are being redrawn. Need to handle this better

**Comment by gaborcsapo** [comment]
You can call the office.delete() function and then create a new Office().

Example usage in stateManager in the BigOfficeStage onEnter property.

Feel free to close this issue after you've read this.

**Comment by jihjihk** [comment]
Thanks @gaborcsapo <3
