### ISSUE TITLE
[FINAL TOUCHES] Game doesn't finish. 

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#122]
The last but one message is never resolved and the game stays in the stopped state.

**Comment by jihjihk** [comment]
we can work on linking the end of the game to the new resources page

**Comment by AliaElKattan** [comment]
yes but I *think* this is actually something else? because their used to be a placeholder ending that says "go to bias training camp" or something like that but now the game freezes before it goes through all the stages of ML lab. not sure if its intentional because youre working on it?

**Comment by jihjihk** [comment]
the bug was because of the scanray tooltip icon being hidden after the first tooltip class being set as inactive and never being updated.

`this.$icon.removeClass(CLASSES.IS_INACTIVE);`

pushing this in the next commit
