### ISSUE TITLE
Re-design the second stage dataset inspector to better communicate color bias

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#134]
<img width="1031" alt="Screen Shot 2019-06-05 at 11 32 59 PM" src="https://user-images.githubusercontent.com/16133987/58971570-51737c80-87ee-11e9-8fa5-9160f90443e1.png">

**Comment by jihjihk** [comment]
ratios of accepted/rejected applicants based evaluated by you
ratios of accepted/rejected applicants evaluated by the machine These stats are meant to reinforce the idea that the bias is present (the ratio statistic should show the yellow people are being favored).

**Comment by gaborcsapo** [comment]
Note: Redesign to make it look like the transition stage conversation
