### ISSUE TITLE
Fix _getRejectedPeople() in dataModule 

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#136]
_getRejectedPeople() current logic is exclude all accepted index to get the rejected index array, but this doesn't take into account of all the people in line that are pending evaluation. Need to fix

**Comment by gaborcsapo** [comment]
Well, if you get an applicant and ignore him, that's a rejection, no? The current logic should be <all the people you were shown> minus <all the people accepted>

**Comment by jihjihk** [comment]
It takes into account of all the people in line because the lastindex of datamodule is of people that are in line. in ML lab not all candidates would have been looked through. can be deprioritized for now, depending on how accurate we want the prediction to be
