### ISSUE TITLE
Change ResumeViewer UI from PIXI to HTML component

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#14]

**Comment by jihjihk** [comment]
will work on this after issue 14

**Comment by mklasinc** [comment]
I just refactored the CVViewer, now it's an html component, you can find it in `components/ui/ui-resume`, I'll keep this open to do some tests and make sure everything works but afterwards we can close this!

**Comment by mklasinc** [comment]
<img width="1303" alt="screen shot 2019-02-24 at 13 14 54" src="https://user-images.githubusercontent.com/19872136/53299069-3def6780-3836-11e9-8e11-926ea928ac32.png">
