### ISSUE TITLE
[MANUAL HIRING] Even if time runs out the investor message still says 'solid work'

### ISSUE THREAD

**Issue by mklasinc** [AliaElKattan/survivalofthebestfit#148]

**Comment by jihjihk** [comment]
@mklasinc i saw the change to using state - I will leave this with you. Also there's another issue that the time runs out but we still progress with the stage. So I am assuming the repeat is still being handled as progressing through.

**Comment by mklasinc** [comment]
I'm on it!

**Comment by mklasinc** [comment]
done!
