### ISSUE TITLE
[ML stage] "task completed" text mistimed

### ISSUE THREAD

**Issue by AliaElKattan** [AliaElKattan/survivalofthebestfit#149]
![image](https://user-images.githubusercontent.com/7271371/59152384-1ae26f80-8a43-11e9-9da4-f0701d6e9116.png)

the 'task completed' text showed up in the beginning of the stage, and stayed throughout

**Comment by jihjihk** [comment]
this is a stupid bug - somehow the hiring goal in text template is 6 for the last stage. maybe we should have a better way of doing data integrity check.

**Comment by jihjihk** [comment]
<img width="617" alt="Screen Shot 2019-06-09 at 12 22 16 PM" src="https://user-images.githubusercontent.com/16133987/59155034-01c4d780-8ab2-11e9-8e0b-cf29dd37f301.png">
