### ISSUE TITLE
[ML stage] wait for e-mail in dataset inspector

### ISSUE THREAD

**Issue by AliaElKattan** [AliaElKattan/survivalofthebestfit#150]
as soon as I opened the dataset inspector, first thing I saw was the e-mail, so I clicked on it, which closed the inspector... we can't assume that the users will know to *first* look for the name, then open the e-mail - so maybe we should only show the e-mail either after a certain period of time or after the user clicks on the right CV?

**Comment by jihjihk** [comment]
yeah so its a bit hard since the cv inspector is hover event. It'd be much easier to handle with click. @mklasinc what do you think ?

**Comment by jihjihk** [comment]
also for the sake of mobile

**Comment by jihjihk** [comment]
its now changed from hover to click and the email pops up with a delay after the first click. But it would be nice to have a slide up animation added!!

**Comment by gaborcsapo** [comment]
Can we check if the name of the resume clicked is Elvan? And only fire the event if it was Elvan?

**Comment by jihjihk** [comment]
Our dear elvan. Let me look into it
