### ISSUE TITLE
Celebratory welcome page

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#158]
Current welcome page shows a mellow, blue, lonely person. The imagery has nothing with the celbratory feeling we'd want the user to feel while we're congratulating them.

![Screenshot from 2019-06-11 21-40-48](https://user-images.githubusercontent.com/13856404/59305179-9fc2c880-8c91-11e9-87d2-a36caada0874.png)

**Comment by gaborcsapo** [comment]
MVP: replace person with a celebratory emoji.
https://emojiterra.com/party-popper/

**Comment by AliaElKattan** [comment]
should we change the big text to "congratulations!"?
