### ISSUE TITLE
User decision script

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#16]

**Comment by gaborcsapo** [comment]
To make this more actionable we can break it down:
- Story intro (you won funcing, now you have to create the company)
- Gameplay tutorial ( "You have to drag people to the office or the trash based on what you think of their CVs)
- Progress between office stages ("hire more and more and more")
- ML lab transition (why ml and what it is)
- ML lab training (this is what's happening when training a model)
- uncovering (CEO asking questions that lead you to realize bias) coordinate w Alia (she asked us to nag her so give her deadlines XD )

**Comment by jihjihk** [comment]
[Google doc](https://docs.google.com/document/d/1I2k_QgOdyuRwG57aOeK6G30LDYJrz9S8RGTl0v_Gfkk/edit)

**Comment by jihjihk** [comment]
closing for now
