### ISSUE TITLE
Weird green stuff on landing page

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#162]
![Screenshot from 2019-06-11 23-21-50](https://user-images.githubusercontent.com/13856404/59310901-c0921a80-8c9f-11e9-82a7-a6fe5a6e74bb.png)
![Screenshot from 2019-06-11 23-21-37](https://user-images.githubusercontent.com/13856404/59310903-c0921a80-8c9f-11e9-84c3-58041eeb83b5.png)

**Comment by AliaElKattan** [comment]
don't see this on any of the 4 browsers/devices I tried the game on

**Comment by jihjihk** [comment]
I dont see it either.
