### ISSUE TITLE
Modify instruction box UI to have choice A and B

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#17]

**Comment by mklasinc** [comment]
added support for multiple response buttons in the instruction box - just to make sure we're on the same page @jihjihk , what's important is only that we have multiple responses in text, there's no functionality changes involved, right (=it doesn't matter if you click option A or option B, you always get taken to the next stage). If that's the case, then we can close the issues (I'll let you do it once you make sure the thing works as you wanted it to).

**Comment by mklasinc** [comment]
HOW IT WORKS:
- You have to pass a `responses` option to the TextboxUI, which has to be an array with your text responses.
- I've setup a `reponses` array prop in `textTemplate.js` already, feel free to swap/edit the text!
- then, whenever you create a new textbox, just pass the responses prop to the class instance
```
new TextBoxUI({
   content: txt.mediumOfficeStage.messageFromVc,
   responses: txt.mediumOfficeStage.responses,
   show: true
 });
```

**Comment by mklasinc** [comment]
<img width="659" alt="Screen Shot 2019-03-09 at 18 25 58" src="https://user-images.githubusercontent.com/19872136/54074910-d48d4100-4298-11e9-9c06-20b8a5272eed.png">
