### ISSUE TITLE
[feedback] Narrative: explain why bias happens even if you're intentionally unbiased

### ISSUE THREAD

**Issue by AliaElKattan** [AliaElKattan/survivalofthebestfit#171]
several people asked about this: we either leave it as "its hardcoded bc this is an educational experience" or explain that theres a larger & more historic dataset at hand and clarify that part of the story better.

**Comment by gaborcsapo** [comment]
Make sure people don't leave the experience disappointed. Set the expectations right at the end so that people don't expect a diff ending. Let them know this is a single story.
