### ISSUE TITLE
Move conversation text into textTemplate.js

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#19]
Can we keep text templating consistent. We don't have have text be defined in a bunch of different places. @mklasinc Unless you have any objections, can you please move the demo-conversation into the textTemplate.js

**Comment by jihjihk** [comment]
let me work on this now as I update the gameplay script for all stages @mklasinc

**Comment by jihjihk** [comment]
merged to master
