### ISSUE TITLE
Change CV viewer color based on candidate's color

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#28]
you can refer to this from office.js as a reference!

`
            let color = cvCollection.smallOfficeStage[this.uniqueCandidateIndex].color;
            console.log(color);
            texture = (color === "yellow") ? yellowPersonTexture : bluePersonTexture; 
`

**Comment by AliaElKattan** [comment]
on it

**Comment by mklasinc** [comment]
@AliaElKattan  is this done? otherwise i can do it!
