### ISSUE TITLE
Running `npm run dev-all`

### ISSUE THREAD

**Issue by mklasinc** [AliaElKattan/survivalofthebestfit#5]
Hey everyone,
this more of a PSA than an issue but still:

with Browserify, the Javascript code/libs/modules get bundled up and then the bundle is put in a destination -`/dist` - folder. Earlier the JS bundles were included in the versioning and were tracked by git, but now I added the `dist/` folder to gitignore to remove unwanted artifacts during development.

Now, when you run `npm run dev-all`, a shell script will check if there's an existing `/dist` folder in your `/public` directory - if it is, the script will just clean up the folder, otherwise it will create a new dist folder from scratch. `npm run dev-all` also starts a nodemon server and tracks all JS/SCSS code changes and recompiles the javascript/css bundles as soon as you make the changes, so I really recommend you use `npm run dev-all` in future development.

Since we're running on different computers/OS's, please pull the latest version (master or dev branch) and check that the npm script runs fine - I can close this issue once everyone confirms things work ok.

**Comment by jihjihk** [comment]
Yep the script works fine for me. Should we also add the final game-bundle and main-bundle to .gitignore? @mklasinc

**Comment by AliaElKattan** [comment]
![image](https://user-images.githubusercontent.com/7271371/52912301-fcf0d380-32c8-11e9-8d88-4d2e1dc71b1a.png)

**Comment by gaborcsapo** [comment]
@AliaElKattan, just do an npm install. 

Can we add npm install to the dev-all command?

Works fine at me, except I have to run it w sudo, because the the the clean script is trying to delete from a write only folder ot sth.

**Comment by AliaElKattan** [comment]
that's what I did already, a couple times

**Comment by gaborcsapo** [comment]
can you try to run it in an Admin Command Prompt? In my case the clean-dist script needed sudo, so I guess on Windows that translates to the admin cmd

**Comment by gaborcsapo** [comment]
@AliaElKattan Is this resolved?

**Comment by gaborcsapo** [comment]
@AliaElKattan, can you pull and try?

The issue was with the script. It had a recursive remove, which requires root access so we had to call it with sudo. On Windows, it would work if the Command Prompt was opened in Administrator mode (+ had to clean npm cache for some reason).

To avoid this problem in the future, I switched the script to a node-module that doesn't require root access to clean a folder.

**Comment by AliaElKattan** [comment]
I CAN RUN!!! THANK YOU GABOR
