### ISSUE TITLE
[ML Lab View] Make stage more interactive

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#68]
* Backend - making sure the specific person to investigate is inserted into the list and hard code the predict function to return false for that name
* CV inspector - Look for the specific name of the candidate
* CV inspector - Ask for the specific reason why it was rejected. Little task reminder box in the corner, once clicked on the person conversation box asking why this person is rejected. Miha can point you to the designs. 
* When hovering over people in ML lab stage, have pop-ups saying that you don’t need to do anything, you automated yourself out of your job

**Comment by mklasinc** [comment]
https://docs.google.com/document/d/1SMXQiBX41HdZMB5jtMGQbpFZU9HFvGKH2m1RWtxp-Yo/edit

**Comment by jihjihk** [comment]
for a given candidate:
* blue
* index after n number of the initial ML start
* cv features to be above > average
