### ISSUE TITLE
Refactoring code structure

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#7]
Public
	Assets
	Components
		Game (Visual)
			Pixi
				Desk.js
				mlOffice.js
				Office.js
				Person.js
			UI
				Timer
				cvViewer
				instructionBubble
				taskTImer
UI-base.js
Choice-button
				Conversation-box
				Mobile-notification
				Replica

	
		Shared
			Buttons
			
	JS (controllers)
		Common
			Textures.js
			Utils.js
		Constants
			Classes.js (classesEnum)
			Events.js (eventsEnum)
		Machine-learning
			Svm.js (own folder)
		gameState.js (game-manager)
		Main.js (entry.js)
		Shared.js (game-setup)
		
		
	SCSS
		Main.scss

**Comment by gaborcsapo** [comment]
done. Excuse me if I broke something, I tested every feature I section I know about.
