### ISSUE TITLE
Create new individual dev branch/Delete unused branches

### ISSUE THREAD

**Issue by jihjihk** [AliaElKattan/survivalofthebestfit#8]

**Comment by gaborcsapo** [comment]
How about we all develop in our own alia-dev, jihyun-dev, gabor-dev, miha-dev branches and when we're done with a feature we merge with master?

My opinion: Having master, dev, and feature branches makes sense to me if master was the production environment. We're not in production yet, so let's not overcomplicate branching.

**Comment by gaborcsapo** [comment]
@AliaElKattan , @mklasinc  did you guys manage to set it up?

**Comment by mklasinc** [comment]
I set up mine and published

**Comment by mklasinc** [comment]
also i started deleting my old branches
