### ISSUE TITLE
Changing the ML lab timeline manager from time-based to number of people hired

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#83]

**Comment by jihjihk** [comment]
* timeout event - we need to pause the animation when instruction pops up
* change the timeline to be based on the # of people hired

**Comment by jihjihk** [comment]
We should also try to fix the relationship between lab and timeline manager

**Comment by jihjihk** [comment]
@mklasinc for awareness - I will pick this up

**Comment by jihjihk** [comment]
* expose hired count from data servers
* start and stop animation when showing messages
